version: '3.8'
services:
  postgres:
    container_name: postgres
    image: "postgres:16"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '1548'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432
    volumes:
      - ./backend/database.sql:/docker-entrypoint-initdb.d/init-database.sql
    networks:
      - mynetwork
  backend:
    build:
      dockerfile: Dockerfile
      context: "./backend"
    depends_on:
      - postgres
    networks:
      - mynetwork
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1548
      - POSTGRES_DB=database
  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge